### ISSUE TITLE
train_config for STEGO

### ISSUE THREAD

**Issue by ramdhan1989** [ChenLiu-1996/CUTS#10]
Hi,
would you mind sharing example of train_config to run STEGO ?
`python step02_precompute_knns.py --train-config ./train_config/train_config_retina_seed2022.yaml`

Thank you

**Comment by ChenLiu-1996** [comment]
Hi, I believe it is already in the repository, under `comparison/STEGO/CUTS_scripts/`

`train_config` is inside `comparison/STEGO/CUTS_scripts/train_config/`

**Comment by ramdhan1989** [comment]
Ok thanks
