### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by wwzz-max** [ChenLiu-1996/CUTS#5]
Hello,

I recently came across your research project on GitHub and was truly impressed by it. I am particularly interested in the dataset mentioned in your paper titled "CUTS: A Fully Unsupervised Framework for Medical Image Segmentation".

Would it be possible for you to share the dataset with me? It would greatly assist my academic research. I assure you that I will only use it for academic purposes and will adhere to any terms and conditions you might have regarding its use.

If you're comfortable sharing, could you please send it to my email at [1101310283@qq.com](mailto:1101310283@qq.com)?

Thank you very much for considering my request. I genuinely appreciate your contribution to the academic community and look forward to diving deeper into the insights your dataset might offer.

Best regards,
wwzz-max

**Comment by ChenLiu-1996** [comment]
Thank you for your support. The datasets that we can currently share are already included in the `./data/` folder. We are still working with collaborators on copyright issues regarding other datasets.

**Comment by wwzz-max** [comment]
Thank you for your patient response. Does this mean that I can only use the two datasets in the ./data/ folder for now? And it's possible to use other datasets in the future if circumstances allow?

**Comment by ChenLiu-1996** [comment]
Yes that's right. At the moment we only have those available, but we will work out the logistics and put other datasets once the paperwork etc. are ready.

**Comment by wwzz-max** [comment]
Hello, can you provide some other datasets from the paper now?

**Comment by ChenLiu-1996** [comment]
I can share the brain ventricles dataset if you ask for it via email. `chen.liu.cl2482@yale.edu`.

**Comment by wwzz-max** [comment]
Thank you so much, I've already sent you an email.
