### ISSUE TITLE
STEGO

### ISSUE THREAD

**Issue by wwzz-max** [ChenLiu-1996/CUTS#7]
2  | cluster_probe            | ClusterLookup              | 700   
3  | linear_probe             | Conv2d                     | 710   
4  | decoder                  | Conv2d                     | 27.3 K
5  | cluster_metrics          | UnsupervisedMetrics        | 0     
6  | linear_metrics           | UnsupervisedMetrics        | 0     
7  | test_cluster_metrics     | UnsupervisedMetrics        | 0     
8  | test_linear_metrics      | UnsupervisedMetrics        | 0     
9  | linear_probe_loss_fn     | CrossEntropyLoss           | 0     
10 | crf_loss_fn              | ContrastiveCRFLoss         | 0     
11 | contrastive_corr_loss_fn | ContrastiveCorrelationLoss | 0     
-------------------------------------------------------------------------
231 K     Trainable params
21.7 M    Non-trainable params
21.9 M    Total params
87.606    Total estimated model params size (MB)
Epoch 0: 100%|██████████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.92it/s, v_num=2]Attempted to log scalar metric test/linear/mIoU:█████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.47it/s]
nan
Attempted to log scalar metric test/linear/Accuracy:
nan
Attempted to log scalar metric test/cluster/mIoU:
nan
Attempted to log scalar metric test/cluster/Accuracy:
nan
Hello, I encountered this problem in STEGO.

**Comment by ChenLiu-1996** [comment]
I believe this is the expected behavior. The nan is coming from the fact that no ground truth is provided. In this case, it is learning with self-supervision and produces the corresponding predictions.
